### ISSUE TITLE
TypeError: buffer is too small for requested array python

### ISSUE THREAD

**Issue by pankhurivanjani** [TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani#4]
Link to short Code: [ros2sub-python](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/master/sensor-drivers_python/ros2sub.py)

****Exact pointer to error in code: [link1](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/master/sensor-drivers_python/ros2sub.py#L42)

Error causing function line in ROS2 cv_bridge library : [link2](https://github.com/ros-perception/vision_opencv/blob/dashing/cv_bridge/python/cv_bridge/core.py#L179)

As discussed in the issue mentioned in the comment below, the suggested solution has already been implemented in core.py in ros-dashing. 

@jmplaza @vinay0410 can you suggest anything in this regard?

Thanks,

**Comment by pankhurivanjani** [comment]
Version 3.7 will not solve the problem.

This problem is coming again with ROS2 version of colotuner tool.

Relevant github issue : [vision_opencv/issues/213](https://github.com/ros-perception/vision_opencv/issues/213)

**Comment by nik1806** [comment]
With existing implementation of imgmsg_to_cv2() method, the case  of list variable is already taken cared, since the list is getting converted to numpy array.

By going through your error message, i assume it suggest that the data your sending in buffer is less than the requested size give in np.ndarray method.

Please check the size of data your are passing to buffer and define size given to method accordingly.

**Comment by pankhurivanjani** [comment]
Image publisher in ros2 was compressing the images before publishing them, this was creating random values in img.data parameter. Removing the compression feature in publisher fixed this particular issue.

**Comment by vinay0410** [comment]
@pankhurivanjani , Don't you think passing uncompressed images through network will significantly slow down this tool.
It would be better if you read CompressedImage in Subscriber instead of normal Image. 

See this [line](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/c13010f70ddbb1d7a97a9503b8ae6975aadd1ee9/sensor-drivers_python/ros2sub.py#L33), you were passing CompressedImage, and expecting an instance of normal Image.

**Comment by pankhurivanjani** [comment]
Yes, slowing down will happen. I will look into it again.

**Comment by pankhurivanjani** [comment]
Also, currently the colortuner tool is working in ROS2 but just with the first image it accepts, not with the continuous stream of images.

**Comment by pankhurivanjani** [comment]
Yes, this issue of streaming continuous images was solved using multithreading.

Will modify the compressed image thing too for improving efficiency.
